### ISSUE TITLE
Works not anymore in Kodi 19

### ISSUE THREAD

**Issue by Gjaltz** [owagner/kodi2mqtt#39]
Works not anymore in Kodi 19

**Comment by lopesjoao** [comment]
Hi @Gjaltz , I opened a pull request to fix this. You can also find this fixed here: https://github.com/lopesjoao/kodi2mqtt
Best regards.

**Comment by void-spark** [comment]
See also https://github.com/void-spark/kodi2mqtt

**Comment by gu33mis** [comment]
> Hi @Gjaltz , I opened a pull request to fix this. You can also find this fixed here: https://github.com/lopesjoao/kodi2mqtt Best regards.

I've tried running your fork on Raspberry Pi 4 running Kodi with no luck...
- Kodi (19.3 (19.3.0) Git:20211118-a22c0ba337)
- paho-mqtt==1.6.1

Error in kodi.log:

 INFO <general>: CPythonInvoker(1, /home/pi/.kodi/addons/service.mqtt/service.py): script successfully run
 INFO <general>: Python interpreter interrupted by user
 INFO <general>: initializing python engine.
ERROR <general>: Exception in thread 
ERROR <general>: Thread-1
ERROR <general>: :                               
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
ERROR <general>:     
ERROR <general>: self.run()
ERROR <general>: 
ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 892, in run
ERROR <general>:     
ERROR <general>: self._target(*self._args, **self._kwargs)
ERROR <general>: 
ERROR <general>:   File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 3452, in _thread_main
ERROR <general>:     
ERROR <general>: self.loop_forever(retry_first_connection=True)
ERROR <general>: 
ERROR <general>:   File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 1779, in loop_forever
ERROR <general>:     
ERROR <general>: rc = self.loop(timeout, max_packets)
ERROR <general>: 
ERROR <general>:   File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 1181, in loop
ERROR <general>:     
ERROR <general>: rc = self.loop_read(max_packets)
ERROR <general>: 
ERROR <general>:   File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 1572, in loop_read
ERROR <general>:     
ERROR <general>: rc = self._packet_read()
ERROR <general>: 
ERROR <general>:   File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 2310, in _packet_read
ERROR <general>:     
ERROR <general>: rc = self._packet_handle()
ERROR <general>: 
ERROR <general>:   File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 2942, in _packet_handle
ERROR <general>:     
ERROR <general>: return self._handle_connack()
ERROR <general>: 
ERROR <general>:   File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 3029, in _handle_connack
ERROR <general>:     
ERROR <general>: self.on_connect(
ERROR <general>: 
ERROR <general>: TypeError
ERROR <general>: : 
ERROR <general>: connecthandler() takes 3 positional arguments but 4 were given

**Comment by gu33mis** [comment]
> Hi @Gjaltz , I opened a pull request to fix this. You can also find this fixed here: https://github.com/lopesjoao/kodi2mqtt Best regards.

I've tried running your fork on Raspberry Pi 4 running Kodi with no luck...

Kodi (19.3 (19.3.0) Git:20211118-a22c0ba337)
paho-mqtt==1.6.1
Error in kodi.log:

INFO : CPythonInvoker(1, /home/pi/.kodi/addons/service.mqtt/service.py): script successfully run
INFO : Python interpreter interrupted by user
INFO : initializing python engine.
ERROR : Exception in thread
ERROR : Thread-1
ERROR : :
ERROR : Traceback (most recent call last):
ERROR : File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
ERROR :
ERROR : self.run()
ERROR :
ERROR : File "/usr/lib/python3.9/threading.py", line 892, in run
ERROR :
ERROR : self._target(*self._args, **self._kwargs)
ERROR :
ERROR : File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 3452, in _thread_main
ERROR :
ERROR : self.loop_forever(retry_first_connection=True)
ERROR :
ERROR : File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 1779, in loop_forever
ERROR :
ERROR : rc = self.loop(timeout, max_packets)
ERROR :
ERROR : File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 1181, in loop
ERROR :
ERROR : rc = self.loop_read(max_packets)
ERROR :
ERROR : File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 1572, in loop_read
ERROR :
ERROR : rc = self._packet_read()
ERROR :
ERROR : File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 2310, in _packet_read
ERROR :
ERROR : rc = self._packet_handle()
ERROR :
ERROR : File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 2942, in _packet_handle
ERROR :
ERROR : return self._handle_connack()
ERROR :
ERROR : File "/home/pi/.kodi/addons/service.mqtt/lib/client.py", line 3029, in _handle_connack
ERROR :
ERROR : self.on_connect(
ERROR :
ERROR : TypeError
ERROR : :
ERROR : connecthandler() takes 3 positional arguments but 4 were given
